spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  main:
    allow-circular-references: true
#jwt
jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization



